name: build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: debug ls
        run: ls -la
      - uses: nttld/setup-ndk@v1
        with:
            ndk-version: r27
      - name: compile
        run: |
          CC=$(find "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" -name 'aarch64-linux-android28-clang' | head -1)
          echo "CC=$CC"
          $CC -O0 -static -fPIE -pie -o futex_poc_pd1728 IonStack/CVE-2026-43499/poc/poc.c -pthread
      - uses: actions/upload-artifact@v4
        with:
          name: futex_poc_pd1728
          path: futex_poc_pd1728
